import javax.swing.*;

public class Naive extends javax.swing.JFrame {

    // Omitted code generated by GUI builder.

    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField;

    public JButton getButton() {
        return jButton1;
    }

    public JLabel getLabel() {
        return jLabel1;
    }

    public JTextField getTextField() {
        return jTextField;
    }

}